### ISSUE TITLE
RedisModule_GetCommand not found in Redis 6

### ISSUE THREAD

**Issue by The-night-elves** [RedisLabsModules/redismodule-rs#398]
### Description

The `api` macro in `src/context/commands.rs` uses the `RedisModule_GetCommand` command, which does not exist in Redis 6.

### Environment

* Operating System: Amazon Linux 2023
* Redis Version: 6.2.14
* redismodule-rs Version: v2.0.8

### Error Message

<hello> RedisModule_GetCommand does not exists
Module /mnt/e/test/redis_module_server_6_02/target/release/libredis_module_server_6_02.so initialization failed. Module not loaded
Can't load module from /mnt/e/test/redis_module_server_6_02/target/release/libredis_module_server_6_02.so: server aborting

### Relevant Code

```rust
// lib.rs
use redis_module::{redis_module, Context, RedisResult, RedisString, REDIS_OK};

fn hello_mul(_ctx: &Context, _args: Vec<RedisString>) -> RedisResult  {
    REDIS_OK
}

redis_module! {
    name: "hello",
    version: 1,
    allocator: (redis_module::alloc::RedisAlloc, redis_module::alloc::RedisAlloc),
    data_types: [],
    commands: [
        ["hello.test", hello_mul, "", 1, 1, 1],
    ],
}
```

Cargo.toml
```toml
[package]
name = "redis_module_server_6_02"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
redis-module = { git = "https://github.com/RedisLabsModules/redismodule-rs", tag = "v2.0.8"}
```

Run `cargo build --release`
load module 

```bash
redis6-server --port 6380 --loadmodule /mnt/e/test/redis_module_server_6_02/target/release/libredis_module_server_6_02.so
```

### Expected Result

The api macro should be compatible with Redis 6, or provide a compatible solution.
